---
extends:
  - '@commitlint/config-conventional'
rules:
  header-max-length:
    - 2
    - always
    - 128
  body-max-line-length:
    - 2
    - always
    - 128
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - format
      - perf
      - refactor
      - revert
      - style
      - test
      - ui
